# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FitSquad' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitSquad
  pod 'Firebase/Core'
  pod 'FBSDKLoginKit'
  
  target 'FitSquadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitSquadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
